[package]
name = "discorn"
version = "0.1.0"
authors = ["sternj <sternj@brandeis.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"

[dependencies.serenity]
version = "0.8"
default-features = true 